[project]
name = "vmemu"

[subdir.deps]

[target.vmemu]
type = "static"
compile-features = ["cxx_std_20"]

sources = [
    "src/**.cpp",
    "include/**.hpp",
]

include-directories = [
    "include",
]

link-libraries = [
    "vmprofiler",
    "unicorn",
    "cli-parser",
]

compile-definitions = [
    "NOMINMAX"
]
